name: Deploy Cookbook to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Dependencies installieren
        run: pip install mkdocs-material mkdocs-callouts

      - name: Website bauen & deployen
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
